[project]
name = "ooai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.2.0",
    "markitdown[all]>=0.1.1",
    "playwright>=1.51.0",
    "pytest>=8.3.5",
]

[project.scripts]
ooai = "main:main"